### 게시물 목록 조회
GET http://localhost:8080/posts
Accept: application/json

###

### 특정 게시물 조회 (ID: 1)
GET http://localhost:8080/posts/1
Accept: application/json

###

### 특정 게시물 조회 (ID: 2)
GET http://localhost:8080/posts/2
Accept: application/json